### ISSUE TITLE
Functions in JavaScript

### ISSUE THREAD

**Issue by RidwanAdebosin** [Oluwasetemi/javascript-note#12]
- Recursion and Stack
- Rest Parameters and Spread Syntax
- Closure and Variable Scope
- Global Object
- Function Object, NFE and `new Function` syntax
- Scheduling: `setTimeout` and `setInterval` | `process.nextTick` | `requestAnimationFrame` | `microtasks`
- Decorators and Forwarding, call/apply, bind
- Function binding
- Arrow functions in details

**Comment by Oluwasetemi** [comment]
How is this going? @RidwanAdebosin. If you need any help please do let me know

**Comment by RidwanAdebosin** [comment]
It is going well for now boss.

**Comment by Oluwasetemi** [comment]
Any update on this @RidwanAdebosin

**Comment by RidwanAdebosin** [comment]
I should be making a PR tomorrow. I am 70% done with it sir.
