### ISSUE TITLE
modules

### ISSUE THREAD

**Issue by Joker4mas** [Oluwasetemi/javascript-note#23]
The module Topic which covers  Import, export, and dynamic import

**Comment by Joker4mas** [comment]
Task done 😎. Thank you sir for the privilege

**Comment by Joker4mas** [comment]
This was really good experience for to be able to contribute and also learn slidev.

**Comment by Oluwasetemi** [comment]
yes you are welcome to the word of open source, i will assign reviewers

**Comment by Oluwasetemi** [comment]
I wll leave the issue open till it is review by the team @joker4mas
