### ISSUE TITLE
Bug 

### ISSUE THREAD

**Issue by Rolalove** [Oluwasetemi/javascript-note#8]
An error occurred on this slide, check the terminal for more information.

slide failed to load SyntaxError: The requested module '/@fs/C:/Users/USER/Desktop/Rola/javascript-note/node_modules/lz-string/libs/lz-string.js?v=4d6fe572' does not provide an export named 'default' (at Monaco.vue?t=1727510182614:3:8)

That is the exact error on the console. This is only affecting slides with monaco-run.

What can be done to fix this error please.

**Comment by Oluwasetemi** [comment]
Can you give more context into the code it was trying to run with `monaco-run` @Rolalove
