### ISSUE TITLE
Code Quality

### ISSUE THREAD

**Issue by ChidinmaNwosu** [Oluwasetemi/javascript-note#9]
I will be working on Linters, Code formatters, Types, Test, Debugging in the browser, and A peep into performance.

**Comment by Oluwasetemi** [comment]
@ChidinmaNwosu, any update on this

**Comment by ChidinmaNwosu** [comment]
> @ChidinmaNwosu, any update on this

Yes, almost done with the debugging in the browser part. I will send it in tomorrow, i just don't have any idea on what to do for the peep into performance part

**Comment by Oluwasetemi** [comment]
You can leave it, I will add it. The main goal is to think about lighthouse in the browser and the perforomance tab. Check web.dev learn performance section
